[2024-01-04T13:44:50.574+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: snow_dag.is_snow_api_ready scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-01-04T13:44:50.590+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: snow_dag.is_snow_api_ready scheduled__2024-01-03T00:00:00+00:00 [queued]>
[2024-01-04T13:44:50.591+0000] {taskinstance.py:2171} INFO - Starting attempt 3 of 3
[2024-01-04T13:44:50.685+0000] {taskinstance.py:2192} INFO - Executing <Task(HttpSensor): is_snow_api_ready> on 2024-01-03 00:00:00+00:00
[2024-01-04T13:44:50.688+0000] {standard_task_runner.py:60} INFO - Started process 614 to run task
[2024-01-04T13:44:50.691+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'snow_dag', 'is_snow_api_ready', 'scheduled__2024-01-03T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/servicenow_dag.py', '--cfg-path', '/tmp/tmpoh8dht67']
[2024-01-04T13:44:50.693+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask is_snow_api_ready
[2024-01-04T13:44:50.821+0000] {task_command.py:423} INFO - Running <TaskInstance: snow_dag.is_snow_api_ready scheduled__2024-01-03T00:00:00+00:00 [running]> on host 4a92eecc6669
[2024-01-04T13:44:50.967+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='prady1900' AIRFLOW_CTX_DAG_ID='snow_dag' AIRFLOW_CTX_TASK_ID='is_snow_api_ready' AIRFLOW_CTX_EXECUTION_DATE='2024-01-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-03T00:00:00+00:00'
[2024-01-04T13:44:50.967+0000] {http.py:130} INFO - Poking: api/now/table/incident
[2024-01-04T13:44:50.987+0000] {base.py:83} INFO - Using connection ID 'snow_api_id' for task execution.
[2024-01-04T13:44:53.286+0000] {base.py:293} INFO - Success criteria met. Exiting.
[2024-01-04T13:44:53.296+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=snow_dag, task_id=is_snow_api_ready, execution_date=20240103T000000, start_date=20240104T134450, end_date=20240104T134453
[2024-01-04T13:44:53.395+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-04T13:44:53.434+0000] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
